// <auto-generated />
using System;
using InvoiceProcessor.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceProcessor.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331072239_AddCatalogItemAutoCreated")]
    partial class AddCatalogItemAutoCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("InvoiceProcessor.Web.Models.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("InvoiceProcessor.Web.Models.CatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AutoCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErpItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalCode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutoCreated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uom")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ErpItemCode")
                        .IsUnique();

                    b.HasIndex("InternalCode");

                    b.ToTable("CatalogItems");
                });

            modelBuilder.Entity("InvoiceProcessor.Web.Models.CostCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CostCenters");
                });

            modelBuilder.Entity("InvoiceProcessor.Web.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailSubject")
                        .HasColumnType("TEXT");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GrossTotal")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PdfHash")
                        .IsUnique();

                    b.HasIndex("SupplierId", "InvoiceNo", "InvoiceDate", "GrossTotal");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("InvoiceProcessor.Web.Models.ExtractArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractedJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.ToTable("ExtractArtifacts");
                });

            modelBuilder.Entity("InvoiceProcessor.Web.Models.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("CostCenterCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LineNo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MatchConfidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MatchedItemId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Qty")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uom")
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarehouseCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("MatchedItemId");

                    b.ToTable("InvoiceLines");
                });

            modelBuilder.Entity("InvoiceProcessor.Web.Models.PostingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErpDocNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "Status");

                    b.ToTable("PostingJobs");
                });

            modelBuilder.Entity("InvoiceProcessor.Web.Models.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AliasesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErpName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VatNo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("InvoiceProcessor.Web.Models.SupplierItemMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierItemMappings");
                });

            modelBuilder.Entity("InvoiceProcessor.Web.Models.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("InvoiceProcessor.Web.Models.AuditEvent", b =>
                {
                    b.HasOne("InvoiceProcessor.Web.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("InvoiceProcessor.Web.Models.Document", b =>
                {
                    b.HasOne("InvoiceProcessor.Web.Models.Supplier", "Supplier")
                        .WithMany("Documents")
                        .HasForeignKey("SupplierId");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("InvoiceProcessor.Web.Models.ExtractArtifact", b =>
                {
                    b.HasOne("InvoiceProcessor.Web.Models.Document", "Document")
                        .WithOne("ExtractArtifact")
                        .HasForeignKey("InvoiceProcessor.Web.Models.ExtractArtifact", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("InvoiceProcessor.Web.Models.InvoiceLine", b =>
                {
                    b.HasOne("InvoiceProcessor.Web.Models.Document", "Document")
                        .WithMany("InvoiceLines")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceProcessor.Web.Models.CatalogItem", "MatchedItem")
                        .WithMany()
                        .HasForeignKey("MatchedItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Document");

                    b.Navigation("MatchedItem");
                });

            modelBuilder.Entity("InvoiceProcessor.Web.Models.PostingJob", b =>
                {
                    b.HasOne("InvoiceProcessor.Web.Models.Document", "Document")
                        .WithMany("PostingJobs")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("InvoiceProcessor.Web.Models.SupplierItemMapping", b =>
                {
                    b.HasOne("InvoiceProcessor.Web.Models.CatalogItem", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceProcessor.Web.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogItem");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("InvoiceProcessor.Web.Models.Document", b =>
                {
                    b.Navigation("ExtractArtifact");

                    b.Navigation("InvoiceLines");

                    b.Navigation("PostingJobs");
                });

            modelBuilder.Entity("InvoiceProcessor.Web.Models.Supplier", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
